// Generated by gencpp from file range_sensor/RangeMeasurementArray.msg
// DO NOT EDIT!


#ifndef RANGE_SENSOR_MESSAGE_RANGEMEASUREMENTARRAY_H
#define RANGE_SENSOR_MESSAGE_RANGEMEASUREMENTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <range_sensor/RangeMeasurement.h>

namespace range_sensor
{
template <class ContainerAllocator>
struct RangeMeasurementArray_
{
  typedef RangeMeasurementArray_<ContainerAllocator> Type;

  RangeMeasurementArray_()
    : header()
    , measurements()  {
    }
  RangeMeasurementArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , measurements(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::range_sensor::RangeMeasurement_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::range_sensor::RangeMeasurement_<ContainerAllocator> >::other >  _measurements_type;
  _measurements_type measurements;





  typedef boost::shared_ptr< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> const> ConstPtr;

}; // struct RangeMeasurementArray_

typedef ::range_sensor::RangeMeasurementArray_<std::allocator<void> > RangeMeasurementArray;

typedef boost::shared_ptr< ::range_sensor::RangeMeasurementArray > RangeMeasurementArrayPtr;
typedef boost::shared_ptr< ::range_sensor::RangeMeasurementArray const> RangeMeasurementArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::range_sensor::RangeMeasurementArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::range_sensor::RangeMeasurementArray_<ContainerAllocator1> & lhs, const ::range_sensor::RangeMeasurementArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.measurements == rhs.measurements;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::range_sensor::RangeMeasurementArray_<ContainerAllocator1> & lhs, const ::range_sensor::RangeMeasurementArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace range_sensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f973ebf7b330759b20c6280d292daea9";
  }

  static const char* value(const ::range_sensor::RangeMeasurementArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf973ebf7b330759bULL;
  static const uint64_t static_value2 = 0x20c6280d292daea9ULL;
};

template<class ContainerAllocator>
struct DataType< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "range_sensor/RangeMeasurementArray";
  }

  static const char* value(const ::range_sensor::RangeMeasurementArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"RangeMeasurement[] measurements\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: range_sensor/RangeMeasurement\n"
"std_msgs/Header header\n"
"\n"
"int32 id       # ID of anchor\n"
"float64 range  # distance to anchor\n"
;
  }

  static const char* value(const ::range_sensor::RangeMeasurementArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.measurements);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RangeMeasurementArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::range_sensor::RangeMeasurementArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::range_sensor::RangeMeasurementArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "measurements[]" << std::endl;
    for (size_t i = 0; i < v.measurements.size(); ++i)
    {
      s << indent << "  measurements[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::range_sensor::RangeMeasurement_<ContainerAllocator> >::stream(s, indent + "    ", v.measurements[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RANGE_SENSOR_MESSAGE_RANGEMEASUREMENTARRAY_H
