// Generated by gencpp from file mavros_msgs/MotorSetpoint.msg
// DO NOT EDIT!


#ifndef MAVROS_MSGS_MESSAGE_MOTORSETPOINT_H
#define MAVROS_MSGS_MESSAGE_MOTORSETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mavros_msgs
{
template <class ContainerAllocator>
struct MotorSetpoint_
{
  typedef MotorSetpoint_<ContainerAllocator> Type;

  MotorSetpoint_()
    : header()
    , setpoint()  {
      setpoint.assign(0.0);
  }
  MotorSetpoint_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , setpoint()  {
  (void)_alloc;
      setpoint.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<float, 8>  _setpoint_type;
  _setpoint_type setpoint;





  typedef boost::shared_ptr< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> const> ConstPtr;

}; // struct MotorSetpoint_

typedef ::mavros_msgs::MotorSetpoint_<std::allocator<void> > MotorSetpoint;

typedef boost::shared_ptr< ::mavros_msgs::MotorSetpoint > MotorSetpointPtr;
typedef boost::shared_ptr< ::mavros_msgs::MotorSetpoint const> MotorSetpointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mavros_msgs::MotorSetpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mavros_msgs::MotorSetpoint_<ContainerAllocator1> & lhs, const ::mavros_msgs::MotorSetpoint_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.setpoint == rhs.setpoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mavros_msgs::MotorSetpoint_<ContainerAllocator1> & lhs, const ::mavros_msgs::MotorSetpoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mavros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b3cd59674ada67977a971a5213a7739";
  }

  static const char* value(const ::mavros_msgs::MotorSetpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b3cd59674ada679ULL;
  static const uint64_t static_value2 = 0x77a971a5213a7739ULL;
};

template<class ContainerAllocator>
struct DataType< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mavros_msgs/MotorSetpoint";
  }

  static const char* value(const ::mavros_msgs::MotorSetpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"# motor throttle value [-1..1]\n"
"float32[8] setpoint\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mavros_msgs::MotorSetpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorSetpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mavros_msgs::MotorSetpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mavros_msgs::MotorSetpoint_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "setpoint[]" << std::endl;
    for (size_t i = 0; i < v.setpoint.size(); ++i)
    {
      s << indent << "  setpoint[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.setpoint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAVROS_MSGS_MESSAGE_MOTORSETPOINT_H
