// Generated by gencpp from file controller/newMsg.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_NEWMSG_H
#define CONTROLLER_MESSAGE_NEWMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct newMsg_
{
  typedef newMsg_<ContainerAllocator> Type;

  newMsg_()
    {
    }
  newMsg_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::controller::newMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::newMsg_<ContainerAllocator> const> ConstPtr;

}; // struct newMsg_

typedef ::controller::newMsg_<std::allocator<void> > newMsg;

typedef boost::shared_ptr< ::controller::newMsg > newMsgPtr;
typedef boost::shared_ptr< ::controller::newMsg const> newMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::newMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::newMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::controller::newMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::newMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::newMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::newMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::newMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::newMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::newMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::controller::newMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::newMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/newMsg";
  }

  static const char* value(const ::controller::newMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::newMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::controller::newMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::newMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct newMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::newMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::controller::newMsg_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_NEWMSG_H
